services:
  - type: web
    name: adresponse-app
    env: python
    buildCommand: ./build.sh
    startCommand: python src/main.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
